### ISSUE TITLE
CSS | Investigate why things appear differently deployed and locally

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#373]

**Comment by CamillaHorneland** [comment]
Investigate why images work locally and not deployed. And pather otherwise works locally but not deployed.
Simply pressing for example "profile" locally takes me to pages/user/index.html and I see the content on the page. If I press the same place public I get the same url, but don't see content just "404 file not found"
Deployed:
<img width="1141" alt="Skjermbilde 2023-10-12 kl  16 27 55" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/4c42d236-dd83-4a85-8b86-965b8d1a0d49">

<img width="1162" alt="Skjermbilde 2023-10-12 kl  16 28 19" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/e9bcd249-5e15-4e43-860b-1e0576524a6a">

Local:
<img width="1149" alt="Skjermbilde 2023-10-12 kl  16 28 38" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/8b384f55-1dd2-484f-a57c-2c3773316b05">

<img width="1159" alt="Skjermbilde 2023-10-12 kl  16 28 46" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/42ab505e-ca88-496e-b54a-d8264d245f35">

Profile page deployed: 
<img width="1134" alt="Skjermbilde 2023-10-12 kl  16 37 35" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/b00b85f5-8175-4527-ad28-fab7be33c221">

Profile page Local:
<img width="1147" alt="Skjermbilde 2023-10-12 kl  16 37 49" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/9afc9cf9-03f8-4305-852d-836eb502ce41">

**Comment by Fermain** [comment]
Looking at the workflow file, I wonder if this is the cause:

```yaml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist'
```

This looks like it is only uploading root files + dist, which could be why we aren't getting the right results. We could try changing this to:

```yaml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './'
```
